default_language_version:
    python: python3

repos:
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-json
    - id: check-yaml
    - id: detect-private-key
    - id: check-added-large-files
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      args: ["--ignore=W503,E501,E203", --max-line-length=88]

